name: OpenGL Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cache
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/*.cpp') }}
      - name: Checking for opengl libraries
        run: |
          ls /usr/lib | grep glew

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libglew-dev \
            freeglut3-dev \
            mesa-common-dev \
            libglu1-mesa-dev

      - name: Build
        run: |
          g++ -m64 -I/usr/include src/main.cpp -o myprogram -L/usr/lib -lGLEW -lglut -lGL -lGLU -fpermissive


      - name: Run Tests
        run: |
          # Run your tests or executable here

